AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Hello World en Go (invocación manual)

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2
    Architectures:
      - x86_64

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldFunction
      Handler: bootstrap
      CodeUri: .
      Role: arn:aws:iam::<ACCOUNT_ID>:role/lambda-execution-role
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Hello World en Go (invocación manual)

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2
    Architectures:
      - x86_64

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldFunction
      Handler: bootstrap
      CodeUri: .
      Role: arn:aws:iam::<ACCOUNT_ID>:role/lambda-execution-role
